/**
 * SeismoGuard AI - Multi-Hazard Geophysical & Meteorological Data Service
 * 
 * Provides validated geospatial datasets and telemetry for 7 natural disaster categories:
 * - Earthquake (แผ่นดินไหว)
 * - Tsunami (สึนามิ & ทุ่นเตือนภัย DART)
 * - Flood (น้ำท่วม & ลุ่มน้ำโทรมาตร)
 * - Landslide (ดินโคลนถล่ม & ดินสไลด์)
 * - Storm (พายุหมุนเขตร้อน & ลมเฉือน)
 * - Wildfire (ไฟป่า & จุดความร้อน VIIRS/MODIS)
 * - Volcano (ภูเขาไฟระเบิด & เถ้าถ่านภูเขาไฟในอาเซียน)
 * 
 * Source Agencies: TMD, DDPM (ปภ.), RID (กรมชลประทาน), GISTDA, HII (สสน.), DMR, NOAA, USGS
 */

import { DisasterType, DisasterIncident, DisasterFilterOption } from '../types/disaster';

export const DISASTER_FILTER_OPTIONS: DisasterFilterOption[] = [
  {
    id: 'earthquake',
    label: 'แผ่นดินไหว',
    labelEn: 'Earthquake',
    badge: 'SEISMIC',
    color: '#06b6d4', // cyan-500
    count: 14,
    sourceAgency: 'TMD / DMR / USGS',
    description: 'รอยเลื่อนมีพลัง, คลื่นไหวสะเทือน 3 แกน และสถานีเครือข่ายแห่งชาติ',
  },
  {
    id: 'tsunami',
    label: 'สึนามิ & ทุ่นอันดามัน',
    labelEn: 'Tsunami & Ocean Buoy',
    badge: 'OCEANIC',
    color: '#3b82f6', // blue-500
    count: 6,
    sourceAgency: 'ปภ. (DDPM) / NOAA DART',
    description: 'ทุ่นตรวจวัดคลื่นยักษ์ DART 23401, 23461 และหอเตือนภัย 6 จังหวัดอันดามัน',
  },
  {
    id: 'flood',
    label: 'น้ำท่วม & ลุ่มน้ำวิกฤต',
    labelEn: 'Flood & River Basin',
    badge: 'HYDROLOGY',
    color: '#0284c7', // sky-600
    count: 7,
    sourceAgency: 'กรมชลประทาน (RID) / สสน. (HII)',
    description: 'สถานีโทรมาตรวัดระดับน้ำ, อัตราการระบายเขื่อน และจุดเสี่ยงน้ำท่วมฉับพลัน',
  },
  {
    id: 'landslide',
    label: 'ดินโคลนถล่ม & ดินสไลด์',
    labelEn: 'Landslide & Mudflow',
    badge: 'GEOTECH',
    color: '#d97706', // amber-600
    count: 5,
    sourceAgency: 'กรมทรัพยากรธรณี (DMR)',
    description: 'พื้นที่ลาดเชิงเขาเสี่ยงภัย, ปริมาณน้ำฝนสะสม 24 ชม. และความชื้นในดิน',
  },
  {
    id: 'storm',
    label: 'พายุหมุนเขตร้อน & ลมแรง',
    labelEn: 'Tropical Storm & Cyclone',
    badge: 'METEOROLOGY',
    color: '#8b5cf6', // purple-500
    count: 4,
    sourceAgency: 'กรมอุตุนิยมวิทยา (TMD)',
    description: 'เส้นทางเดินพายุ, เรดาร์ตรวจวัดกลุ่มฝน และรัศมีลมกระโชกแรงในอ่าวไทย',
  },
  {
    id: 'wildfire',
    label: 'ไฟป่า & จุดความร้อน',
    labelEn: 'Wildfire & Hotspots',
    badge: 'SATELLITE',
    color: '#f97316', // orange-500
    count: 6,
    sourceAgency: 'GISTDA / VIIRS / MODIS',
    description: 'จุดความร้อนจากดาวเทียม, พื้นที่ป่าสงวนเสี่ยงภัย และการแพร่กระจาย PM2.5',
  },
  {
    id: 'volcano',
    label: 'ภูเขาไฟระเบิดในอาเซียน',
    labelEn: 'Volcano Activity',
    badge: 'VOLCANOLOGY',
    color: '#ef4444', // red-500
    count: 4,
    sourceAgency: 'PVMBG / PHIVOLCS / Smithsonian',
    description: 'แนวภูเขาไฟที่ยังมีพลังในสุมาตรา-ชวา และระดับการแจ้งเตือนการบิน (VONA)',
  },
];

export const NATURAL_DISASTER_INCIDENTS: DisasterIncident[] = [
  // -------------------------------------------------------------
  // 1. TSUNAMI (สึนามิ & ทุ่นทางทะเล)
  // -------------------------------------------------------------
  {
    id: 'tsu-dart-23401',
    type: 'tsunami',
    title: 'ทุ่นตรวจวัดคลื่นสึนามิในมหาสมุทรอินเดีย (DART Station 23401)',
    titleTh: 'ทุ่นเตือนภัยสึนามิระยะไกล ทะเลอันดามัน (DART 23401)',
    location: 'ห่างจากเกาะภูเก็ตไปทางทิศตะวันตกเฉียงใต้ ~965 กม.',
    province: 'ทะเลอันดามัน (สากล)',
    latitude: 8.890,
    longitude: 92.580,
    severity: 'normal',
    status: 'ONLINE / ACTIVE',
    timestamp: Date.now() - 4 * 60 * 1000,
    source: 'ปภ. ศูนย์เตือนภัยพิบัติแห่งชาติ / NOAA NDBC',
    description: 'ทุ่นตรวจวัดคลื่นน้ำลึกเชื่อมต่อดาวเทียม Iridium ส่งสัญญาณความกดดันใต้ท้องทะเลแบบเรียลไทม์ทุก 15 นาที',
    radiusKm: 120,
    metrics: [
      { label: 'ระดับผิวน้ำทะเล (BPR)', value: '3,480.25', unit: 'เมตร', trend: 'stable' },
      { label: 'ความผันแปรของคลื่น', value: '±0.04', unit: 'เมตร', trend: 'stable' },
      { label: 'สถานะทุ่นเตือนภัย', value: 'ปกติ (Normal)', unit: 'โหมดเฝ้าระวัง' },
    ],
  },
  {
    id: 'tsu-dart-23461',
    type: 'tsunami',
    title: 'ทุ่นตรวจวัดคลื่นสึนามิใกล้ชายฝั่งไทย (DART Station 23461)',
    titleTh: 'ทุ่นเตือนภัยสึนามิระยะใกล้ ชายฝั่งพังงา-สิมิลัน (DART 23461)',
    location: 'ห่างจากหมู่เกาะสิมิลัน จ.พังงา ไปทางทิศตะวันตก ~340 กม.',
    province: 'พังงา (ทะเลอันดามัน)',
    latitude: 8.250,
    longitude: 95.800,
    severity: 'normal',
    status: 'ONLINE / ACTIVE',
    timestamp: Date.now() - 8 * 60 * 1000,
    source: 'ปภ. กรมป้องกันและบรรเทาสาธารณภัย',
    description: 'ทุ่นเฝ้าระวังด่านหน้าของประเทศไทยเพื่อแจ้งเตือนล่วงหน้า 30-45 นาที ก่อนคลื่นกระทบชายฝั่ง',
    radiusKm: 85,
    metrics: [
      { label: 'ระดับผิวน้ำทะเล (BPR)', value: '2,240.10', unit: 'เมตร', trend: 'stable' },
      { label: 'ความสูงคลื่นนัยสำคัญ', value: '0.85', unit: 'เมตร', trend: 'stable' },
      { label: 'เวลาส่งสัญญาณล่าสุด', value: '5 นาทีที่แล้ว', unit: 'Satellite Pass' },
    ],
  },
  {
    id: 'tsu-tower-patong',
    type: 'tsunami',
    title: 'หอเตือนภัยสึนามิหาดป่าตอง (Patong Beach Tsunami Warning Tower)',
    titleTh: 'หอเตือนภัยสึนามิชายฝั่ง หาดป่าตอง ภูเก็ต',
    location: 'ชายหาดป่าตอง อ.กะทู้',
    province: 'ภูเก็ต',
    latitude: 7.896,
    longitude: 98.297,
    severity: 'normal',
    status: 'STANDBY / READY',
    timestamp: Date.now() - 15 * 60 * 1000,
    source: 'ศูนย์เตือนภัยพิบัติแห่งชาติ (NDWC)',
    description: 'หอสัญญาณเตือนภัยพร้อมระบบไซเรนพลังงานแสงอาทิตย์ 5 ภาษา และระบบถ่ายทอดวิทยุฉุกเฉิน',
    metrics: [
      { label: 'ระบบกระจายเสียง', value: '130', unit: 'dB (พร้อมใช้งาน)', trend: 'stable' },
      { label: 'เส้นทางอพยพคลื่นยักษ์', value: '4 เส้นทางหลัก', unit: 'สู่พื้นที่สูง' },
      { label: 'เวลาเตือนภัยสูงสุด', value: '35', unit: 'นาทีก่อนคลื่นถึง' },
    ],
  },
  {
    id: 'tsu-tower-khaolak',
    type: 'tsunami',
    title: 'หอเตือนภัยสึนามิเขาหลัก (Khao Lak Coastal Siren Tower)',
    titleTh: 'หอเตือนภัยสึนามิอนุสรณ์สถานเรือ ต.813 เขาหลัก',
    location: 'ต.คึกคัก อ.ตะกั่วป่า',
    province: 'พังงา',
    latitude: 8.650,
    longitude: 98.250,
    severity: 'normal',
    status: 'STANDBY / READY',
    timestamp: Date.now() - 22 * 60 * 1000,
    source: 'ปภ. ศูนย์เตือนภัยพิบัติแห่งชาติ',
    description: 'จุดเฝ้าระวังพิเศษชายฝั่งอันดามันตอนบน พร้อมจุดรวมพลอาคารอพยพหลบภัยคลื่นสึนามิ',
    metrics: [
      { label: 'ความพร้อมระบบไซเรน', value: '100%', unit: 'Solar + Batt', trend: 'stable' },
      { label: 'จุดหลบภัยสูงสุด', value: '+28', unit: 'เมตรเหนือระดับน้ำทะเล' },
    ],
  },
  {
    id: 'tsu-tower-phiphi',
    type: 'tsunami',
    title: 'หอเตือนภัยเกาะพีพีดอน (Ko Phi Phi Tsunami Alarm System)',
    titleTh: 'หอเตือนภัยสึนามิอ่าวโละดาลัม เกาะพีพี',
    location: 'อ่าวโละดาลัม เกาะพีพีดอน อ.เมืองกระบี่',
    province: 'กระบี่',
    latitude: 7.740,
    longitude: 98.770,
    severity: 'normal',
    status: 'STANDBY / READY',
    timestamp: Date.now() - 30 * 60 * 1000,
    source: 'อบต.อ่าวนาง / ปภ. กระบี่',
    description: 'ระบบตรวจวัดคลื่นชายฝั่งพร้อมไฟสัญญาณเตือนฉุกเฉินความเข้มสูงสำหรับเกาะท่องเที่ยวหนาแน่น',
    metrics: [
      { label: 'ระบบประกาศเตือน', value: '5 ภาษา', unit: 'ไทย/อังกฤษ/จีน/ญี่ปุ่น/เยอรมัน' },
      { label: 'ระยะทางสู่จุดปลอดภัย', value: '450', unit: 'เมตร (เขาจุดชมวิว)' },
    ],
  },
  {
    id: 'tsu-tower-ranong',
    type: 'tsunami',
    title: 'สถานีตรวจวัดระดับน้ำทะเลเกาะพยาม (Ko Phayam Tidal Station)',
    titleTh: 'สถานีโทรมาตรคลื่นชายฝั่ง เกาะพยาม ระนอง',
    location: 'เกาะพยาม อ.เมืองระนอง',
    province: 'ระนอง',
    latitude: 9.735,
    longitude: 98.402,
    severity: 'normal',
    status: 'ONLINE',
    timestamp: Date.now() - 12 * 60 * 1000,
    source: 'กรมอุทกศาสตร์ กองทัพเรือ',
    description: 'สถานีตรวจวัดน้ำขึ้น-น้ำลง และคลื่นผิดปกติฝั่งทะเลอันดามันตอนบนติดชายแดนเมียนมา',
    metrics: [
      { label: 'ระดับน้ำทะเลตรวจวัด', value: '+1.42', unit: 'เมตร (รทก.)' },
      { label: 'ความเร็วคลื่นลม', value: '18', unit: 'นอต' },
    ],
  },

  // -------------------------------------------------------------
  // 2. FLOOD (น้ำท่วม & โทรมาตรลุ่มน้ำ)
  // -------------------------------------------------------------
  {
    id: 'fld-c13-chainat',
    type: 'flood',
    title: 'เขื่อนเจ้าพระยา สถานี C.13 ชัยนาท (Chao Phraya Barrage Dam)',
    titleTh: 'สถานีโทรมาตรวัดน้ำเขื่อนเจ้าพระยา (C.13) ชัยนาท',
    location: 'ต.บางหลวง อ.สรรพยา',
    province: 'ชัยนาท',
    latitude: 15.158,
    longitude: 100.180,
    severity: 'warning',
    status: 'เฝ้าระวังระดับน้ำสูง (ALERT LEVEL 2)',
    timestamp: Date.now() - 10 * 60 * 1000,
    source: 'กรมชลประทาน (RID) ศูนย์ปฏิบัติการน้ำอัจฉริยะ (SWOC)',
    description: 'จุดควบคุมการระบายน้ำสู่พื้นที่ลุ่มน้ำเจ้าพระยาตอนล่าง (อยุธยา ปทุมธานี นนทบุรี กรุงเทพฯ)',
    radiusKm: 45,
    metrics: [
      { label: 'อัตราการระบายน้ำท้ายเขื่อน', value: '1,450', unit: 'ลบ.ม./วินาที', trend: 'up' },
      { label: 'ระดับน้ำเหนือเขื่อน', value: '16.85', unit: 'ม.(รทก.) / สูงกว่าเกณฑ์ 0.35m' },
      { label: 'ความจุอ่างเก็บน้ำ', value: '78.5%', unit: 'ของความจุเก็บกัก' },
    ],
  },
  {
    id: 'fld-p1-chiangmai',
    type: 'flood',
    title: 'แม่น้ำปิง สถานี P.1 สะพานนวรัฐ เชียงใหม่ (Ping River P.1)',
    titleTh: 'สถานีตรวจวัดระดับน้ำแม่น้ำปิง สะพานนวรัฐ เชียงใหม่',
    location: 'สะพานนวรัฐ เทศบาลนครเชียงใหม่',
    province: 'เชียงใหม่',
    latitude: 18.788,
    longitude: 99.004,
    severity: 'watch',
    status: 'ระดับน้ำเฝ้าระวัง (WATCH)',
    timestamp: Date.now() - 15 * 60 * 1000,
    source: 'สถาบันสารสนเทศทรัพยากรน้ำ (สสน. HII) / กรมชลประทาน',
    description: 'จุดชี้วัดน้ำท่วมเขตเศรษฐกิจเมืองเชียงใหม่ ระดับวิกฤตตลิ่งอยู่ที่ 3.70 - 4.20 เมตร',
    radiusKm: 25,
    metrics: [
      { label: 'ระดับน้ำปัจจุบัน', value: '3.45', unit: 'เมตร (จุดวิกฤต 3.70 ม.)', trend: 'up' },
      { label: 'อัตราการไหล', value: '412', unit: 'ลบ.ม./วินาที' },
      { label: 'ความสูงเทียบตลิ่ง', value: '-0.25', unit: 'เมตรต่ำกว่าขอบตลิ่ง' },
    ],
  },
  {
    id: 'fld-m7-ubon',
    type: 'flood',
    title: 'แม่น้ำมูล สถานี M.7 สะพานเสรีประชาธิปไตย อุบลราชธานี',
    titleTh: 'สถานีตรวจวัดแม่น้ำมูล (M.7) อุบลราชธานี',
    location: 'สะพานเสรีประชาธิปไตย อ.เมืองอุบลราชธานี',
    province: 'อุบลราชธานี',
    latitude: 15.228,
    longitude: 104.856,
    severity: 'watch',
    status: 'เฝ้าระวังน้ำล้นตลิ่ง',
    timestamp: Date.now() - 25 * 60 * 1000,
    source: 'สำนักงานทรัพยากรน้ำแห่งชาติ (สทนช.)',
    description: 'จุดรวมน้ำก่อนไหลลงสู่แม่น้ำโขงที่ อ.โขงเจียม พื้นที่ลุ่มต่ำเสี่ยงน้ำท่วมซ้ำซาก',
    radiusKm: 35,
    metrics: [
      { label: 'ระดับน้ำปัจจุบัน', value: '111.45', unit: 'ม.(รทก.) / ตลิ่ง 112.0 ม.' },
      { label: 'อัตราการไหลสะสม', value: '1,890', unit: 'ลบ.ม./วินาที', trend: 'stable' },
    ],
  },
  {
    id: 'fld-nongkhai-mekong',
    type: 'flood',
    title: 'สถานีตรวจวัดแม่น้ำโขง หนองคาย (Mekong River Hydrological Station)',
    titleTh: 'สถานีวัดระดับน้ำแม่น้ำโขง อ.เมืองหนองคาย',
    location: 'ลานวัฒนธรรมริมโขง อ.เมืองหนองคาย',
    province: 'หนองคาย',
    latitude: 17.883,
    longitude: 102.741,
    severity: 'normal',
    status: 'ระดับน้ำปกติ (NORMAL)',
    timestamp: Date.now() - 35 * 60 * 1000,
    source: 'คณะกรรมาธิการแม่น้ำโขง (MRC) / กรมทรัพยากรน้ำ',
    description: 'เฝ้าระวังปริมาณน้ำหลากจากลุ่มน้ำโขงตอนบนและแม่น้ำสาขาใน สปป.ลาว',
    metrics: [
      { label: 'ระดับน้ำแม่น้ำโขง', value: '9.82', unit: 'เมตร (วิกฤตตลิ่ง 12.20 ม.)' },
      { label: 'แนวโน้ม 24 ชม.', value: '-0.15', unit: 'เมตร (ลดลงเล็กน้อย)', trend: 'down' },
    ],
  },
  {
    id: 'fld-ladpho-bkk',
    type: 'flood',
    title: 'ประตูระบายน้ำคลองลัดโพธิ์อันเนื่องมาจากพระราชดำริ',
    titleTh: 'ประตูระบายน้ำคลองลัดโพธิ์ สมุทรปราการ-กรุงเทพฯ',
    location: 'อ.พระประแดง',
    province: 'สมุทรปราการ',
    latitude: 13.662,
    longitude: 100.542,
    severity: 'normal',
    status: 'เปิดระบายน้ำตามจังหวะน้ำลง (READY)',
    timestamp: Date.now() - 18 * 60 * 1000,
    source: 'สำนักการระบายน้ำ กทม. / กรมชลประทาน',
    description: 'ระบบลัดทางน้ำเพื่อเร่งระบายน้ำเหนือหลากออกสู่อ่าวไทย ร่นระยะทางจาก 18 กม. เหลือ 600 เมตร',
    metrics: [
      { label: 'ประสิทธิภาพการระบาย', value: '45', unit: 'ล้าน ลบ.ม./วัน' },
      { label: 'ระดับน้ำทะเลหนุน', value: '+1.18', unit: 'ม.(รทก.)' },
    ],
  },
  {
    id: 'fld-nan-n1',
    type: 'flood',
    title: 'แม่น้ำน่าน สถานี N.1 สะพานพัฒนาภาคเหนือ น่าน',
    titleTh: 'สถานีวัดระดับน้ำแม่น้ำน่าน (N.1) เมืองน่าน',
    location: 'สะพานพัฒนาภาคเหนือ อ.เมืองน่าน',
    province: 'น่าน',
    latitude: 18.775,
    longitude: 100.771,
    severity: 'normal',
    status: 'ระดับน้ำปกติ',
    timestamp: Date.now() - 40 * 60 * 1000,
    source: 'กรมชลประทาน',
    description: 'เฝ้าระวังน้ำป่าไหลหลากจากเทือกเขาหลวงพระบางและดอยภูคา',
    metrics: [
      { label: 'ระดับน้ำปัจจุบัน', value: '5.20', unit: 'เมตร (วิกฤต 7.00 ม.)' },
      { label: 'อัตราการไหล', value: '380', unit: 'ลบ.ม./วินาที' },
    ],
  },
  {
    id: 'fld-pasak-dam',
    type: 'flood',
    title: 'เขื่อนป่าสักชลสิทธิ์ (Pasak Jolasid Dam)',
    titleTh: 'เขื่อนป่าสักชลสิทธิ์ ลพบุรี-สระบุรี',
    location: 'ต.หนองบัว อ.พัฒนานิคม',
    province: 'ลพบุรี',
    latitude: 14.862,
    longitude: 101.077,
    severity: 'normal',
    status: 'ปกติ (NORMAL)',
    timestamp: Date.now() - 50 * 60 * 1000,
    source: 'กรมชลประทาน',
    description: 'แหล่งกักเก็บน้ำหลักลุ่มน้ำป่าสัก ช่วยตัดยอดน้ำก่อนเข้าสู่พระนครศรีอยุธยา',
    metrics: [
      { label: 'ปริมาตรน้ำในอ่าง', value: '645', unit: 'ล้าน ลบ.ม. (67.2%)' },
      { label: 'อัตราการระบาย', value: '85', unit: 'ลบ.ม./วินาที' },
    ],
  },

  // -------------------------------------------------------------
  // 3. LANDSLIDE (ดินโคลนถล่ม & ดินสไลด์)
  // -------------------------------------------------------------
  {
    id: 'ls-maesalong-cri',
    type: 'landslide',
    title: 'พื้นที่เสี่ยงภัยดินโคลนถล่มวิกฤต ดอยแม่สลอง (Mae Salong Landslide Risk Zone)',
    titleTh: 'จุดเฝ้าระวังดินโคลนถล่ม ดอยแม่สลอง เชียงราย',
    location: 'ต.แม่สลองนอก อ.แม่ฟ้าหลวง',
    province: 'เชียงราย',
    latitude: 20.165,
    longitude: 99.623,
    severity: 'critical',
    status: 'เตือนภัยขั้นวิกฤต (RED WARNING)',
    timestamp: Date.now() - 14 * 60 * 1000,
    source: 'กรมทรัพยากรธรณี (DMR) / ปภ. เชียงราย',
    description: 'ตรวจพบการเลื่อนตัวของมวลดินชั้นบนเนื่องจากปริมาณน้ำฝนสะสมเกิน 150 มม. เสี่ยงดินถล่มปิดทับเส้นทางหลวงชนบท',
    radiusKm: 18,
    metrics: [
      { label: 'ปริมาณฝนสะสม 24 ชม.', value: '178.5', unit: 'มิลลิเมตร (เกณฑ์วิกฤต >150)', trend: 'up' },
      { label: 'ความอิ่มตัวของน้ำในดิน', value: '91.4%', unit: 'Soil Saturation Ratio', trend: 'up' },
      { label: 'ความชันพื้นที่ลาดเชิงเขา', value: '42°', unit: 'Slope Angle' },
    ],
  },
  {
    id: 'ls-doisuthep-chm',
    type: 'landslide',
    title: 'จุดตรวจวัดเสถียรภาพลาดเขา ดอยสุเทพ-ปุย เชียงใหม่',
    titleTh: 'พื้นที่เสี่ยงดินสไลด์และน้ำป่า ดอยสุเทพ-ปุย เชียงใหม่',
    location: 'อุทยานแห่งชาติดอยสุเทพ-ปุย อ.เมืองเชียงใหม่',
    province: 'เชียงใหม่',
    latitude: 18.805,
    longitude: 98.921,
    severity: 'warning',
    status: 'เฝ้าระวังพิเศษ (YELLOW WATCH)',
    timestamp: Date.now() - 20 * 60 * 1000,
    source: 'กรมทรัพยากรธรณี / สถานีเตือนภัยพิบัติดอยสุเทพ',
    description: 'พื้นที่เสี่ยงน้ำป่าไหลหลากลงสู่ลำห้วยแก้ว และดินสไลด์ตามแนวถนนขึ้นพระธาตุดอยสุเทพ',
    radiusKm: 12,
    metrics: [
      { label: 'ปริมาณฝนสะสม 24 ชม.', value: '142.0', unit: 'มิลลิเมตร', trend: 'up' },
      { label: 'ความชื้นในดิน', value: '82.0%', unit: 'Moisture' },
      { label: 'การเคลื่อนตัวตรวจจับ', value: '1.2', unit: 'มม./วัน' },
    ],
  },
  {
    id: 'ls-khaokho-pnb',
    type: 'landslide',
    title: 'พื้นที่ลาดชันเสี่ยงภัยดินสไลด์ เขาค้อ เพชรบูรณ์',
    titleTh: 'จุดเฝ้าระวังดินสไลด์ตามแนวรอยเลื่อน เขาค้อ เพชรบูรณ์',
    location: 'ต.แคมป์สน อ.เขาค้อ',
    province: 'เพชรบูรณ์',
    latitude: 16.634,
    longitude: 101.002,
    severity: 'watch',
    status: 'เฝ้าระวังระดับ 1',
    timestamp: Date.now() - 45 * 60 * 1000,
    source: 'กรมทรัพยากรธรณี',
    description: 'แนวเขาหินทรายผุพังง่าย มีรีสอร์ทและชุมชนตั้งอยู่บนพื้นที่ลาดชันสูง',
    radiusKm: 15,
    metrics: [
      { label: 'ฝนสะสม 24 ชม.', value: '94.5', unit: 'มม.' },
      { label: 'ความเสี่ยงดินถล่ม', value: 'ปานกลาง (Medium)', unit: 'Risk Index' },
    ],
  },
  {
    id: 'ls-betong-yala',
    type: 'landslide',
    title: 'จุดตรวจวัดดินโคลนถล่มเทือกเขาสันกาลาคีรี อ.เบตง ยะลา',
    titleTh: 'พื้นที่เฝ้าระวังดินสไลด์เทือกเขาสันกาลาคีรี เบตง',
    location: 'ต.อัยเยอร์เวง อ.เบตง',
    province: 'ยะลา',
    latitude: 5.774,
    longitude: 101.071,
    severity: 'warning',
    status: 'แจ้งเตือนฝนตกหนักสะสม',
    timestamp: Date.now() - 32 * 60 * 1000,
    source: 'ปภ. ยะลา / กรมทรัพยากรธรณี',
    description: 'เส้นทางสกายวอล์คอัยเยอร์เวงและแนวถนนเชื่อมเบตง เสี่ยงดินสไลด์ปิดทับผิวทาง',
    radiusKm: 20,
    metrics: [
      { label: 'ฝนสะสม 24 ชม.', value: '162.0', unit: 'มม.', trend: 'up' },
      { label: 'ความอิ่มตัวในดิน', value: '86.5%', unit: 'Saturation' },
    ],
  },
  {
    id: 'ls-fang-chm',
    type: 'landslide',
    title: 'พื้นที่เสี่ยงดินถล่มแนวดอยผ้าห่มปก อ.ฝาง เชียงใหม่',
    titleTh: 'จุดเฝ้าระวังดินสไลด์แนวดอยผ้าห่มปก อ.ฝาง',
    location: 'ต.โป่งน้ำร้อน อ.ฝาง',
    province: 'เชียงใหม่',
    latitude: 19.921,
    longitude: 99.213,
    severity: 'watch',
    status: 'เฝ้าระวัง',
    timestamp: Date.now() - 55 * 60 * 1000,
    source: 'อุทยานแห่งชาติดอยผ้าห่มปก / DMR',
    description: 'พื้นที่รอยเลื่อนมีพลังแม่จันร่วมกับสภาพภูมิประเทศหินแกรนิตผุพัง',
    metrics: [
      { label: 'ฝนสะสม 24 ชม.', value: '108.0', unit: 'มม.' },
      { label: 'เสถียรภาพลาดดิน', value: 'Watch', unit: 'Stable' },
    ],
  },

  // -------------------------------------------------------------
  // 4. STORM (พายุหมุนเขตร้อน & ลมแรง)
  // -------------------------------------------------------------
  {
    id: 'stm-cyclone-02w',
    type: 'storm',
    title: 'พายุดีเปรสชันเขตร้อน 02W ในทะเลจีนใต้ตอนล่าง (Tropical Depression 02W)',
    titleTh: 'ศูนย์กลางพายุดีเปรสชันเขตร้อน (02W) เคลื่อนตัวสู่อ่าวไทย',
    location: 'ทะเลจีนใต้ตอนล่าง ห่างจากแหลมญวน ประเทศเวียดนาม 280 กม.',
    province: 'ทะเลจีนใต้ / อ่าวไทยตอนล่าง',
    latitude: 9.200,
    longitude: 106.800,
    severity: 'critical',
    status: 'กำลังทวีกำลังแรง (STORM TRACKING ACTIVE)',
    timestamp: Date.now() - 5 * 60 * 1000,
    source: 'กรมอุตุนิยมวิทยา (TMD) / ศูนย์เตือนไต้ฝุ่นร่วม (JTWC)',
    description: 'ศูนย์กลางพายุความเร็วลม 55 กม./ชม. กำลังเคลื่อนตัวไปทางทิศตะวันตกสู่ปลายแหลมญวนและอ่าวไทย มีแนวโน้มทำให้คลื่นลมแรงในภาคใต้ฝั่งตะวันออก',
    radiusKm: 280,
    pathCoordinates: [
      [9.200, 106.800],
      [9.400, 105.100],
      [9.600, 103.200],
      [9.800, 101.500],
      [10.100, 99.800]
    ],
    metrics: [
      { label: 'ความเร็วลมใกล้ศูนย์กลาง', value: '55 - 65', unit: 'กม./ชม.', trend: 'up' },
      { label: 'ความกดอากาศศูนย์กลาง', value: '1,002', unit: 'hPa' },
      { label: 'ความเร็วในการเคลื่อนที่', value: '18', unit: 'กม./ชม. (ทิศตะวันตก)' },
      { label: 'คลื่นลมในทะเล', value: '2 - 3', unit: 'เมตร (ห่างฝั่ง >3ม.)' },
    ],
  },
  {
    id: 'stm-radar-sattahip',
    type: 'storm',
    title: 'สถานีเรดาร์ตรวจอากาศสัตหีบ กองทัพเรือ (Sattahip Weather Radar)',
    titleTh: 'สถานีเรดาร์ตรวจวัดกลุ่มฝนพายุ สัตหีบ ชลบุรี',
    location: 'เขากรมหลวงชุมพรฯ สัตหีบ',
    province: 'ชลบุรี',
    latitude: 12.665,
    longitude: 100.900,
    severity: 'warning',
    status: 'ตรวจพบกลุ่มเมนพายุฝนฟ้าคะนองรุนแรง',
    timestamp: Date.now() - 12 * 60 * 1000,
    source: 'กรมอุตุนิยมวิทยา / กองทัพเรือ',
    description: 'เรดาร์ตรวจพบแนวกลุ่มฝนฟ้าคะนองเคลื่อนตัวจากอ่าวไทยเข้าสู่อีสเทิร์นซีบอร์ดและ กทม.',
    radiusKm: 180,
    metrics: [
      { label: 'ความแรงกลุ่มฝน (dBZ)', value: '52.5', unit: 'dBZ (ฝนตกหนักมาก)', trend: 'up' },
      { label: 'ลมกระโชกสูงสุดที่ตรวจได้', value: '68', unit: 'กม./ชม.' },
    ],
  },
  {
    id: 'stm-radar-phuket',
    type: 'storm',
    title: 'สถานีเรดาร์ตรวจอากาศภูเก็ต (Phuket Weather Radar Station)',
    titleTh: 'สถานีเรดาร์ตรวจอากาศลมมรสุม ภูเก็ต',
    location: 'ท่าอากาศยานนานาชาติภูเก็ต',
    province: 'ภูเก็ต',
    latitude: 8.113,
    longitude: 98.306,
    severity: 'watch',
    status: 'มรสุมตะวันตกเฉียงใต้กำลังปานกลาง',
    timestamp: Date.now() - 28 * 60 * 1000,
    source: 'กรมอุตุนิยมวิทยา',
    description: 'เฝ้าระวังกลุ่มฝนลมมรสุมและคลื่นลมแรงในทะเลอันดามันตอนบน',
    metrics: [
      { label: 'ความสูงคลื่นนัยสำคัญ', value: '1.80', unit: 'เมตร' },
      { label: 'ความเร็วลมเฉลี่ย', value: '38', unit: 'กม./ชม.' },
    ],
  },
  {
    id: 'stm-radar-phitsanulok',
    type: 'storm',
    title: 'สถานีเรดาร์ตรวจอากาศพิษณุโลก (Phitsanulok Doppler Radar)',
    titleTh: 'สถานีเรดาร์ดอปเปลอร์ตรวจอากาศ พิษณุโลก',
    location: 'อ.เมืองพิษณุโลก',
    province: 'พิษณุโลก',
    latitude: 16.782,
    longitude: 100.278,
    severity: 'normal',
    status: 'สแกนกลุ่มฝน 240 กม.',
    timestamp: Date.now() - 36 * 60 * 1000,
    source: 'กรมอุตุนิยมวิทยา',
    description: 'ครอบคลุมพื้นที่ภาคเหนือตอนล่างและภาคกลางตอนบนเพื่อแจ้งเตือนพายุฤดูร้อน',
    metrics: [
      { label: 'รัศมีการตรวจจับ', value: '240', unit: 'กม.' },
      { label: 'กลุ่มฝนปกคลุม', value: '25%', unit: 'ของพื้นที่สแกน' },
    ],
  },

  // -------------------------------------------------------------
  // 5. WILDFIRE (ไฟป่า & จุดความร้อน)
  // -------------------------------------------------------------
  {
    id: 'wf-omkoi-chm',
    type: 'wildfire',
    title: 'กลุ่มจุดความร้อนวิกฤต ป่าสงวนแห่งชาติ อ.อมก๋อย เชียงใหม่',
    titleTh: 'คลัสเตอร์ไฟป่าและจุดความร้อน ป่าสงวนแห่งชาติ อ.อมก๋อย',
    location: 'ต.นาเกียน อ.อมก๋อย',
    province: 'เชียงใหม่',
    latitude: 17.801,
    longitude: 98.358,
    severity: 'critical',
    status: 'วิกฤตไฟป่ารุนแรง (CRITICAL HOTSPOT)',
    timestamp: Date.now() - 11 * 60 * 1000,
    source: 'GISTDA ดาวเทียม Suomi NPP (VIIRS) / กรมป่าไม้',
    description: 'ตรวจพบจุดความร้อนสะสมต่อเนื่อง 18 จุด ในป่าลึกเข้าถึงยาก มีการส่งเฮลิคอปเตอร์ทิ้งน้ำดับไฟป่า',
    radiusKm: 22,
    metrics: [
      { label: 'จำนวนจุดความร้อน (Hotspots)', value: '18', unit: 'จุด (ดาวเทียม VIIRS)', trend: 'up' },
      { label: 'ดัชนีฝุ่น PM2.5 ในพื้นที่', value: '135.0', unit: 'µg/m³ (มีผลกระทบต่อสุขภาพ)', trend: 'up' },
      { label: 'พื้นที่ความเสียหายประเมิน', value: '380', unit: 'ไร่' },
      { label: 'ดัชนีความเสี่ยงไฟป่า (FWI)', value: 'Extreme', unit: 'รุนแรงมาก' },
    ],
  },
  {
    id: 'wf-pai-mhs',
    type: 'wildfire',
    title: 'จุดความร้อนอุทยานแห่งชาติห้วยน้ำดัง อ.ปาย แม่ฮ่องสอน',
    titleTh: 'กลุ่มไฟป่าอุทยานแห่งชาติห้วยน้ำดัง อ.ปาย แม่ฮ่องสอน',
    location: 'ต.แม่นาเติง อ.ปาย',
    province: 'แม่ฮ่องสอน',
    latitude: 19.358,
    longitude: 98.441,
    severity: 'critical',
    status: 'ไฟป่ารุกคืบ (RED FIRE ALERT)',
    timestamp: Date.now() - 16 * 60 * 1000,
    source: 'GISTDA / กรมอุทยานแห่งชาติ สัตว์ป่า และพันธุ์พืช',
    description: 'ไฟป่าลุกลามบนสันเขาแนวชายแดน ควันไฟสะสมในแอ่งกระทะเมืองปาย ค่าคุณภาพอากาศอยู่ในเกณฑ์สีแดง',
    radiusKm: 25,
    metrics: [
      { label: 'จุดความร้อน Hotspots', value: '24', unit: 'จุด', trend: 'up' },
      { label: 'ค่าฝุ่น PM2.5 ตรวจวัด', value: '168.4', unit: 'µg/m³ (อันตราย)', trend: 'up' },
      { label: 'ความชื้นสัมพัทธ์ในอากาศ', value: '18%', unit: 'แห้งจัด' },
    ],
  },
  {
    id: 'wf-doiphukha-nan',
    type: 'wildfire',
    title: 'จุดความร้อนแนวป่าดอยภูคา จ.น่าน (Doi Phu Kha Forest Fire)',
    titleTh: 'จุดความร้อนแนวป่าธรรมชาติ ดอยภูคา น่าน',
    location: 'อุทยานแห่งชาติดอยภูคา อ.ปัว',
    province: 'น่าน',
    latitude: 19.200,
    longitude: 101.080,
    severity: 'warning',
    status: 'กำลังควบคุมเพลิง',
    timestamp: Date.now() - 34 * 60 * 1000,
    source: 'กรมอุทยานแห่งชาติฯ',
    description: 'ชุดเหยี่ยวไฟและชาวบ้านร่วมทำแนวกันไฟเพื่อสกัดเพลิงไม่ให้ลามเข้าสู่ป่าต้นน้ำ',
    radiusKm: 14,
    metrics: [
      { label: 'จุดความร้อน Hotspots', value: '11', unit: 'จุด' },
      { label: 'ค่าฝุ่น PM2.5', value: '88.0', unit: 'µg/m³' },
    ],
  },
  {
    id: 'wf-saiyok-kan',
    type: 'wildfire',
    title: 'ไฟป่าเทือกเขาตะนาวศรี อ.ไทรโยค กาญจนบุรี',
    titleTh: 'จุดความร้อนป่าเบญจพรรณ อ.ไทรโยค กาญจนบุรี',
    location: 'ต.ไทรโยค อ.ไทรโยค',
    province: 'กาญจนบุรี',
    latitude: 14.120,
    longitude: 99.050,
    severity: 'warning',
    status: 'เฝ้าระวังแนวไฟ',
    timestamp: Date.now() - 48 * 60 * 1000,
    source: 'GISTDA / สำนักบริหารพื้นที่อนุรักษ์ที่ 3',
    description: 'ไฟป่าในป่าเต็งรังและไผ่แห้งตายซาก กำลังทำแนวป้องกันร่วมกับทหารพราน',
    radiusKm: 16,
    metrics: [
      { label: 'จุดความร้อน Hotspots', value: '14', unit: 'จุด' },
      { label: 'ทิศทางลม', value: 'ตะวันตกเฉียงใต้ 15 กม./ชม.' },
    ],
  },
  {
    id: 'wf-khaoyai-korat',
    type: 'wildfire',
    title: 'จุดตรวจจับความร้อนขอบอุทยานแห่งชาติเขาใหญ่',
    titleTh: 'จุดเฝ้าระวังไฟป่ารอบแนวเขาใหญ่ นครราชสีมา',
    location: 'ต.หมูสี อ.ปากช่อง',
    province: 'นครราชสีมา',
    latitude: 14.430,
    longitude: 101.370,
    severity: 'normal',
    status: 'ปกติ ควบคุมได้ (CONTAINED)',
    timestamp: Date.now() - 65 * 60 * 1000,
    source: 'อุทยานแห่งชาติเขาใหญ่',
    description: 'ตรวจพบจุดเผาเศษวัชพืชริมแนวกันชน เจ้าหน้าที่เข้าควบคุมดับสนิทแล้ว',
    metrics: [
      { label: 'จุดความร้อน Hotspots', value: '2', unit: 'จุด (ดับแล้ว)' },
      { label: 'ค่าฝุ่น PM2.5', value: '32.0', unit: 'µg/m³ (คุณภาพดี)' },
    ],
  },
  {
    id: 'wf-chiangdao-chm',
    type: 'wildfire',
    title: 'ดอยหลวงเชียงดาว เขตรักษาพันธุ์สัตว์ป่าเชียงใหม่',
    titleTh: 'จุดตรวจวัดความเสี่ยงไฟป่า ดอยหลวงเชียงดาว',
    location: 'ต.เชียงดาว อ.เชียงดาว',
    province: 'เชียงใหม่',
    latitude: 19.395,
    longitude: 98.888,
    severity: 'watch',
    status: 'เฝ้าระวังพื้นที่อนุรักษ์ชั้นสูง',
    timestamp: Date.now() - 24 * 60 * 1000,
    source: 'เขตรักษาพันธุ์สัตว์ป่าเชียงดาว',
    description: 'พื้นที่สงวนชีวมณฑลยูเนสโก มีการจัดเวรยามเฝ้าระวังแนวหน้าผาตลอด 24 ชั่วโมง',
    metrics: [
      { label: 'จุดความร้อน', value: '0', unit: 'จุดในเขตรังวัด' },
      { label: 'ความเสี่ยงไฟป่า FWI', value: 'High', unit: 'เฝ้าระวัง' },
    ],
  },

  // -------------------------------------------------------------
  // 6. VOLCANO (ภูเขาไฟระเบิดในภูมิภาคอาเซียน)
  // -------------------------------------------------------------
  {
    id: 'vol-marapi-sumatra',
    type: 'volcano',
    title: 'ภูเขาไฟมารูปี เกาะสุมาตราตะวันตก (Mount Marapi Volcano)',
    titleTh: 'ภูเขาไฟมารูปี สุมาตราตะวันตก ประเทศอินโดนีเซีย',
    location: 'เทือกเขาบูกิตบาริซัน สุมาตราตะวันตก อินโดนีเซีย (ห่างจากยะลา ~640 กม.)',
    province: 'สุมาตราตะวันตก (อินโดนีเซีย)',
    latitude: -0.381,
    longitude: 100.473,
    severity: 'critical',
    status: 'ปะทุรุนแรง (LEVEL III - SIAGA)',
    timestamp: Date.now() - 9 * 60 * 1000,
    source: 'PVMBG อินโดนีเซีย / Smithsonian GVP',
    description: 'เกิดการปะทุพ่นเถ้าถ่านภูเขาไฟสูงกว่า 3,000 เมตรเหนือยอดเขา และลาวาไหล มีประกาศแจ้งเตือนการบินรหัสสีส้ม (VONA Orange)',
    radiusKm: 180,
    metrics: [
      { label: 'ระดับการเตือนภัย', value: 'Level III (Siaga)', unit: 'เฝ้าระวังขั้นสูง' },
      { label: 'ความสูงกลุ่มเถ้าถ่าน (Plume)', value: '3,200', unit: 'เมตร เหนือยอดเขา', trend: 'up' },
      { label: 'รหัสแจ้งเตือนการบิน', value: 'ORANGE', unit: 'VONA Alert Code' },
      { label: 'ระยะห่างจากชายแดนไทย', value: '640', unit: 'กิโลเมตร' },
    ],
  },
  {
    id: 'vol-sinabung-sumatra',
    type: 'volcano',
    title: 'ภูเขาไฟซีนาบุง เกาะสุมาตราเหนือ (Mount Sinabung Volcano)',
    titleTh: 'ภูเขาไฟซีนาบุง สุมาตราเหนือ (ใกล้ประเทศไทยที่สุด)',
    location: 'ที่ราบสูงคาโร สุมาตราเหนือ อินโดนีเซีย (ห่างจากภูเก็ต ~520 กม.)',
    province: 'สุมาตราเหนือ (อินโดนีเซีย)',
    latitude: 3.170,
    longitude: 98.392,
    severity: 'warning',
    status: 'ปะทุพ่นก๊าซและควันกำมะถัน (LEVEL II - WASPADA)',
    timestamp: Date.now() - 25 * 60 * 1000,
    source: 'ศูนย์ภูเขาไฟวิทยาและบรรเทาภัยทางธรณีวิทยาอินโดนีเซีย (PVMBG)',
    description: 'ภูเขาไฟมีพลังที่ใกล้ภาคใต้ของประเทศไทยที่สุด เฝ้าระวังกระแสลมพาละอองเถ้ากำมะถันสู่พื้นที่ภาคใต้',
    radiusKm: 120,
    metrics: [
      { label: 'ระดับเตือนภัย', value: 'Level II (Waspada)', unit: 'เฝ้าระวัง' },
      { label: 'ระยะทางถึงภูเก็ต', value: '520', unit: 'กิโลเมตร' },
      { label: 'ปริมาณก๊าซ SO2', value: '1,850', unit: 'ตัน/วัน' },
    ],
  },
  {
    id: 'vol-krakatau-sunda',
    type: 'volcano',
    title: 'ภูเขาไฟอานัก กรากะตัว ช่องแคบซุนดา (Anak Krakatau Volcano)',
    titleTh: 'ภูเขาไฟอานัก กรากะตัว ช่องแคบซุนดา อินโดนีเซีย',
    location: 'ช่องแคบซุนดา ระหว่างเกาะชวาและเกาะสุมาตรา',
    province: 'ช่องแคบซุนดา (อินโดนีเซีย)',
    latitude: -6.102,
    longitude: 105.423,
    severity: 'warning',
    status: 'ปะทุต่อเนื่องทางทะเล (LEVEL III - SIAGA)',
    timestamp: Date.now() - 42 * 60 * 1000,
    source: 'PVMBG / Magma Indonesia',
    description: 'ภูเขาไฟกลางทะเลที่มีการประเมินความเสี่ยงต่อการเกิดสึนามิจากการถล่มของไหล่เขาภูเขาไฟ',
    radiusKm: 90,
    metrics: [
      { label: 'ระดับการเตือนภัย', value: 'Level III (Siaga)', unit: 'อันตรายทางทะเล' },
      { label: 'การสั่นไหวแผ่นดินไหวภูเขาไฟ', value: '48 ครั้ง/วัน', unit: 'Volcanic Tremor' },
      { label: 'เขตห้ามเข้าใกล้รัศมี', value: '5', unit: 'กิโลเมตร' },
    ],
  },
  {
    id: 'vol-taal-philippines',
    type: 'volcano',
    title: 'ภูเขาไฟตาอัล ประเทศฟิลิปปินส์ (Taal Volcano)',
    titleTh: 'ภูเขาไฟตาอัล ทะเลสาบตาอัล ประเทศฟิลิปปินส์',
    location: 'จังหวัดบาตังกัส เกาะลูซอน ฟิลิปปินส์',
    province: 'เกาะลูซอน (ฟิลิปปินส์)',
    latitude: 14.002,
    longitude: 120.993,
    severity: 'watch',
    status: 'ปะทุปล่อยไอก๊าซความร้อนสูง (ALERT LEVEL 1)',
    timestamp: Date.now() - 58 * 60 * 1000,
    source: 'PHIVOLCS สถาบันวิทยาแผ่นดินไหวและภูเขาไฟฟิลิปปินส์',
    description: 'ปล่อยควันไอน้ำและก๊าซซัลเฟอร์ไดออกไซด์สูง เฝ้าระวังปรากฏการณ์หมอกควันพิษภูเขาไฟ (Vog)',
    radiusKm: 60,
    metrics: [
      { label: 'ระดับเตือนภัย', value: 'Alert Level 1', unit: 'Low-level Unrest' },
      { label: 'การปล่อยก๊าซ SO2', value: '3,200', unit: 'ตัน/วัน', trend: 'stable' },
    ],
  },
];

/**
 * Filter incidents by disaster type
 */
export function getIncidentsByType(type: DisasterType): DisasterIncident[] {
  return NATURAL_DISASTER_INCIDENTS.filter((inc) => inc.type === type);
}

const DISASTER_COLORS: Record<DisasterType, string> = {
  earthquake: '#06b6d4',
  tsunami: '#3b82f6',
  flood: '#0284c7',
  landslide: '#d97706',
  storm: '#8b5cf6',
  wildfire: '#f97316',
  volcano: '#ef4444',
};

const DISASTER_LABELS: Record<DisasterType, string> = {
  earthquake: 'แผ่นดินไหว',
  tsunami: 'สึนามิ & ทุ่นอันดามัน',
  flood: 'น้ำท่วม & ลุ่มน้ำวิกฤต',
  landslide: 'ดินโคลนถล่ม & ดินสไลด์',
  storm: 'พายุหมุนเขตร้อน & ลมแรง',
  wildfire: 'ไฟป่า & จุดความร้อน',
  volcano: 'ภูเขาไฟระเบิดในอาเซียน',
};

export function getDisasterColor(type: DisasterType): string {
  return DISASTER_COLORS[type] || '#06b6d4';
}

export function getDisasterLabel(type: DisasterType): string {
  return DISASTER_LABELS[type] || 'แผ่นดินไหว';
}
